#!/bin/bash
mkdir -p autogenerated || true #ignore error (it might already exist, although we don't check)

export DOMAIN=dev.practable.io
export HOST="https://${DOMAIN}"

# Create book.service by adding variables to template
export BOOK_PORT=4000
export BOOK_AUDIENCE="${HOST}/book"
export BOOK_SECRET=$(cat ~/secret/v0/book.pat)
export RELAY_SECRET=$(cat ~/secret/v0/relay.pat)
envsubst < ./templates/book.service.template > ./autogenerated/book.service

# create relay.service by adding variables to template
export RELAY_ALLOW_NO_BOOKING_ID=true
export RELAY_AUDIENCE="${HOST}/access"
export RELAY_PORT_ACCESS=3000
export RELAY_PORT_PROFILE=6061
export RELAY_PORT_RELAY=3001
export RELAY_SECRET=$(cat ~/secret/v0/relay.pat)
export RELAY_URL="wss://${DOMAIN}/relay"
envsubst < ./templates/relay.service.template > ./autogenerated/relay.service

# create jump.service by adding variables to template
export JUMP_AUDIENCE="${HOST}/jump"
export JUMP_PORT_ACCESS=3002
export JUMP_PORT_RELAY=3003
export JUMP_SECRET=$(cat ~/secret/v0/jump.pat)
export JUMP_URL="wss://${DOMAIN}/jump"
envsubst < ./templates/jump.service.template > ./autogenerated/jump.service

# create nginx.conf with the ports and routings above
# export vars to avoid $request_uri, $uri etc being replaced with blank
# https://unix.stackexchange.com/questions/294378/replacing-only-specific-variables-with-envsubst
envsubst '${DOMAIN} ${HOST}' < ./templates/nginx-initial.conf.template > ./autogenerated/nginx-initial.conf
envsubst '${BOOK_PORT} ${DOMAIN} ${HOST} ${RELAY_PORT_ACCESS} ${RELAY_PORT_RELAY} ${JUMP_PORT_ACCESS} ${JUMP_PORT_RELAY}' < ./templates/nginx.conf.template > ./autogenerated/nginx.conf


# Create a vars file for ansible, so we can refer to the domain as needed.
export STATIC_REPO_NAME=static-uoe-prod
export STATIC_REPO_URL="https://github.com/practable/${STATIC_REPO_NAME}.git"
export STATIC_SUB_DIRS="['config', 'images', 'info', 'ui']"
export DEV_STATIC_REPO_NAME=static-uoe-dev
export DEV_STATIC_REPO_URL="https://github.com/practable/${DEV_STATIC_REPO_NAME}.git"
export DEV_STATIC_SUB_DIRS="['config', 'images', 'info', 'ui']"
envsubst  < ./templates/vars.yml.template > ./autogenerated/vars.yml






