#!/bin/bash

# tidy up any stale files
rm -rf ./autogenerated
rm -rf ./playbooks

#ignore errors when creating dirs, as they might already exist, although we don't check
mkdir -p autogenerated || true 
mkdir -p book || true
mkdir -p experiments/files || true
mkdir -p jump || true
mkdir -p logs || true 
mkdir -p playbooks || true
mkdir -p relay || true

# Edit to suit your instance

# Directory for services secrets (must contain book.pat, jump.pat, project, relay.pat)
export SECRETS=~/secret/app.practable.io/monitoring
export MAIL_SECRET=~/secret/zoho/mail.yaml

export PROJECT=app-practable-io-alpha

# SSH access
export ZONE=europe-west2-c
export INSTANCE=app-practable-io-alpha-monitoring

# Health check info
export BACKEND_SERVICE=ci-https-redirect-backend-monitoring

# Networking info for services & ansible nginx conf (this stays as ed0 because it's providing the services for ed0)
export INSTANCE_PATH=monitoring
# used in nginx configuration & ansible playbook for lets encrypt
export DOMAIN=app.practable.io
# May be needed for grafana alerts?
export EMAIL=rl.eng@ed.ac.uk
# used in all ansible playbook templates (note usually underscore, not hyphen)
export ANSIBLE_GROUP=app_practable_monitoring

#Prometheus setup
export PROMETHEUS_VERSION="2.54.1"
export PROMETHEUS_DATA_DEVICE="/dev/disk/by-id/google-prometheus-data"
export PROMETHEUS_DATA_MOUNTPOINT="/var/lib/prometheus"
export PROMETHEUS_RETENTION="180d"

# Grafana setup
export GRAFANA_ADMIN_USER="admin"

# Grafana commonly uses these env vars for initial admin bootstrap, but 
# password rotation is only via Grafana API/CLI after startup.
export GRAFANA_ADMIN_PASSWORD="$(cat ${SECRETS}/grafana_admin_password.pat)"

export GRAFANA_DOMAIN="app.practable.io"
export GRAFANA_ROOT_URL="https://app.practable.io/monitoring/"
export GRAFANA_SERVE_FROM_SUB_PATH="true"

export GRAFANA_PORT="3000"

	
###########################################################################
# Do not edit below this line (unless you want a non-standard installation)
###########################################################################

# Do NOT pass and actual secret to a template - instead pass an eval command on a path e.g. `$(cat ${SECRETS}/some_secret.pat)`
# this is to avoid leaking secrets into the git repo if autogenerated files are added inadvertently
# which is possible given that they are deployed into directories for convenience.

export HTTPS_HOST="https://${DOMAIN}/${INSTANCE_PATH}"
export WSS_HOST="wss://${DOMAIN}/${INSTANCE_PATH}"

# create login.sh
envsubst '${INSTANCE} ${PROJECT} ${ZONE}' < ./templates/login.sh.template > ./login.sh
chmod +x ./login.sh

#create health.sh
envsubst '${BACKEND_SERVICE} ${PROJECT}' < ./templates/health.sh.template > ./health.sh
chmod +x ./health.sh

# Pre-install setup playbook (sets up ssh key for RL.Eng@ed.ac.uk machine user account on github)
export PRIVATE_KEY=${SECRETS}/github/id_ed25519
envsubst '${ANSIBLE_GROUP} ${PRIVATE_KEY}' < ./templates/playbook-pre-install-setup.yml.template > ./playbooks/pre-install-setup.yml


# create nginx.conf with the ports and routings above
# export vars to avoid $request_uri, $uri etc being replaced with blank
# https://unix.stackexchange.com/questions/294378/replacing-only-specific-variables-with-envsubst
envsubst '${DOMAIN}' < ./templates/nginx.conf.template > ./autogenerated/nginx.conf

# Create a vars file for ansible, so we can refer to the domain as needed.
envsubst '${DOMAIN}  ${INSTANCE_PATH}' < ./templates/vars.yml.template > ./autogenerated/vars.yml

# Populate our playbooks with group name and other variables
export SSL_DOMAIN="${DOMAIN}/${INSTANCE_PATH}"
envsubst '${ANSIBLE_GROUP}' < ./templates/playbook-configure-kernel.yml.template > ./playbooks/configure-kernel.yml
envsubst '${ANSIBLE_GROUP}' < ./templates/playbook-install-nginx.yml.template > ./playbooks/install-nginx.yml
envsubst '${ANSIBLE_GROUP}' < ./templates/playbook-update-nginx-conf.yml.template > ./playbooks/update-nginx-conf.yml

#Files for prometheus and grafana
envsubst '${PROMETHEUS_DATA_MOUNTPOINT} ${PROMETHEUS_RETENTION}' \
  < ./templates/prometheus.service.template > ./autogenerated/prometheus.service
envsubst '${GRAFANA_ADMIN_USER} ${GRAFANA_ADMIN_PASSWORD} ${GRAFANA_DOMAIN} ${GRAFANA_ROOT_URL} ${GRAFANA_SERVE_FROM_SUB_PATH} ${GRAFANA_PORT}' \
  < ./templates/grafana.override.conf.template > ./autogenerated/grafana.override.conf


# Kernel configuration file
envsubst '${BOOK_AUDIENCE} ${BOOK_SECRET} ${DOMAIN}  ${INSTANCE_PATH}' < ./templates/sysctl-tcp-mem.conf.template > ./autogenerated/tcp-mem.conf
