#!/bin/bash

# tidy up any stale files
rm -rf ./autogenerated
rm -rf ./playbooks

#ignore errors when creating dirs, as they might already exist, although we don't check
mkdir -p autogenerated || true 
mkdir -p logs || true 
mkdir -p playbooks || true

# Edit to suit your instance

export PROJECT=web-practable-io-alpha

# SSH access
export ZONE=europe-west2-c
export INSTANCE=web-practable-io-alpha-default

# Health check info
export BACKEND_SERVICE=ci-https-redirect-backend-default

# used in nginx configuration & ansible playbook for lets encrypt
# TODO temporary setting
export DOMAIN=practable.dev
# Used in ansible nginx playbook for setting up certbot
export EMAIL=rl.eng@ed.ac.uk
# used in all ansible playbook templates (note usually underscore, not hyphen)
export ANSIBLE_GROUP=web_practable_default

###########################################################################
# Do not edit below this line (unless you want a non-standard installation)
###########################################################################

# Do NOT pass and actual secret to a template - instead pass an eval command on a path e.g. `$(cat ${SECRETS}/some_secret.pat)`
# this is to avoid leaking secrets into the git repo if autogenerated files are added inadvertently
# which is possible given that they are deployed into directories for convenience.

export HTTPS_HOST="https://${DOMAIN}"
export WSS_HOST="wss://${DOMAIN}"

# create login.sh
envsubst '${INSTANCE} ${PROJECT} ${ZONE}' < ./templates/login.sh.template > ./login.sh
chmod +x ./login.sh

#create health.sh
envsubst '${BACKEND_SERVICE} ${PROJECT}' < ./templates/health.sh.template > ./health.sh
chmod +x ./health.sh

# create nginx.conf with the ports and routings above
# export vars to avoid $request_uri, $uri etc being replaced with blank
# https://unix.stackexchange.com/questions/294378/replacing-only-specific-variables-with-envsubst
envsubst '${DOMAIN} ${HTTPS_HOST}' < ./templates/nginx.conf.template > ./autogenerated/nginx.conf

envsubst '${ANSIBLE_GROUP} ${SSL_DOMAIN} ${EMAIL}' < ./templates/playbook-install-nginx.yml.template > ./playbooks/install-nginx.yml
